apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  serviceName: "eureka"
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: vmahesh8165/serviceregistry
        ports:
        - containerPort: 8761

---
# internal service - inside cluster
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  # headless service - sticky
  clusterIP: None
  selector:
    app: eureka
  ports:
  - port: 8761
    name: eureka

---
# external service
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - port: 80
    targetPort: 8761

